# Site settings
title: 모두의캠퍼스 - 개발블로그
description: 모두의캠퍼스에서 개발하는 이야기를 담고있어요
baseurl: ""
# url: "https://willianjusten.com.br" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
url: https://moducampus.github.io

# User settings
username: drakejin
user_description: 모두의캠퍼스에서 개발을 하고 있슴다.
email: drakejin@moducampus.com
twitter_username: lorem_ipsum
github_username:  moducampus
gplus_username:  lorem_ipsum
disqus_username: moducampus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: 블로그
    url: /
  - title: 시리즈
    url: /series
  - title: 태그
    url: /tags
  - title: 블로그 소개
    url: /about
  - title: 모캠과 함께
    url: /withus

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
